from flask import Flask
from flask_restful import Api
from scraper3 import *

app = Flask(__name__)
api = Api(app)

api.add_resource(architectsJournalScraper,'/architectsJournalScraper')
api.add_resource(oceanhomeScraper,'/oceanhomeScraper')
api.add_resource(gardengateScraper,'/gardengateScraper')
api.add_resource(restechScraper,'/restechScraper')
api.add_resource(renovatemagScraper,'/renovatemagScraper')
api.add_resource(granddesignsmagazineScraper,'/granddesignsmagazineScraper')
api.add_resource(barandkitchenmagazineScraper,'/barandkitchenmagazineScraper')
api.add_resource(cabmScraper,'/cabmScraper')
api.add_resource(familyhandymanScraper,'/familyhandymanScraper')
api.add_resource(tatlerScraper,'/tatlerScraper')
api.add_resource(nshoremagScraper,'/nshoremagScraper')
api.add_resource(atomicranchScraper,'/atomicranchScraper')
api.add_resource(homebuildingUKScraper,'/homebuildingUKScraper')
api.add_resource(minestomarketScraper,'/minestomarketScraper')
api.add_resource(goodhousekeepingUKScraper,'/goodhousekeepingUKScraper')
api.add_resource(goodhousekeepingScraper,'/goodhousekeepingScraper')
api.add_resource(newYorkerScraper,'/newYorkerScraper')
api.add_resource(moneySenseScraper,'/moneySenseScraper')
api.add_resource(harpersBazaarScraper,'/harpersBazaarScraper')
api.add_resource(glamourScraper,'/glamourScraper')
api.add_resource(hgtvScraper,'/hgtvScraper')
api.add_resource(houseBeautifulUKScraper,'/houseBeautifulUKScraper')
api.add_resource(tatlerasiaScraper,'/tatlerasiaScraper')
api.add_resource(homesandantiquesScraper,'/homesandantiquesScraper')
api.add_resource(luxurypoolsScraper,'/luxurypoolsScraper')
api.add_resource(californiahomedesignScraper,'/californiahomedesignScraper')
api.add_resource(homesandinteriorsscotlandScraper,'/homesandinteriorsscotlandScraper')
api.add_resource(greenlivingmagScraper,'/greenlivingmagScraper')
api.add_resource(smartphotographyScraper,'/smartphotographyScraper')
api.add_resource(biospectrumasiaScraper,'/biospectrumasiaScraper')
api.add_resource(biospectrumindiaScraper,'/biospectrumindiaScraper')
api.add_resource(exhibitechScraper,'/exhibitechScraper')
api.add_resource(businesstravellerScraper,'/businesstravellerScraper')
api.add_resource(visiScraper,'/visiScraper')
api.add_resource(gardenersmagScraper,'/gardenersmagScraper')
api.add_resource(whathifiScraper,'/whathifiScraper')
api.add_resource(sciencefocusScraper,'/sciencefocusScraper')
api.add_resource(popularmechanicsScraper,'/popularmechanicsScraper')
api.add_resource(t3Scraper,'/t3Scraper')
api.add_resource(pcmagScraper,'/pcmagScraper')
api.add_resource(wiredScraper,'/wiredScraper')
api.add_resource(traveltradejournalScraper,'/traveltradejournalScraper')
api.add_resource(thetouriosityScraper,'/thetouriosityScraper')
api.add_resource(retropopmagazineScraper,'/retropopmagazineScraper')
api.add_resource(gomagScraper,'/gomagScraper')
api.add_resource(architecturalDigestScraper,'/architecturalDigestScraper')
api.add_resource(travelandleisureScraper,'/travelandleisureScraper')
api.add_resource(countryfileScraper,'/countryfileScraper')
api.add_resource(indiaoutboundScraper,'/indiaoutboundScraper')
api.add_resource(homesandgardensScraper,'/homesandgardensScraper')
api.add_resource(sahomeownerScraper,'/sahomeownerScraper')
api.add_resource(homemagazineScraper,'/homemagazineScraper')
api.add_resource(motortrendScraper,'/motortrendScraper')
api.add_resource(caranddriverScraper,'/caranddriverScraper')
api.add_resource(roadandtrackScraper,'/roadandtrackScraper')
api.add_resource(topgearmagScraper,'/topgearmagScraper')
api.add_resource(BCwomenUKScraper,'/BCwomenUKScraper')
api.add_resource(inkscapeScraper,'/inkscapeScraper')
api.add_resource(bhgAUScraper,'/bhgAUScraper')
api.add_resource(electronicsforuScraper,'/electronicsforuScraper')
api.add_resource(flowsmartlivingScraper,'/flowsmartlivingScraper')
api.add_resource(indiantextileScraper,'/indiantextileScraper')
api.add_resource(houseandgardenUKScraper,'/houseandgardenUKScraper')
api.add_resource(urbanmagScraper,'/urbanmagScraper')
api.add_resource(apparelScraper,'/apparelScraper')
api.add_resource(mensfolioScraper,'/mensfolioScraper')
api.add_resource(femalemagSGScraper,'/femalemagSGScraper')
api.add_resource(hairmagazineUKScraper,'/hairmagazineUKScraper')
api.add_resource(lofficielScraper,'/lofficielScraper')
api.add_resource(elleScraper,'/elleScraper')
api.add_resource(cosmopolitanUKScraper,'/cosmopolitanUKScraper')
api.add_resource(hotelbusinesScraper,'/hotelbusinesScraper')
api.add_resource(smarthomeworldScraper,'/smarthomeworldScraper')
api.add_resource(psychologytodayScraper1,'/psychologytodayScraper1')
api.add_resource(theEnglishGardenScraper,'/theEnglishGardenScraper')
api.add_resource(newbeautyScraper,'/newbeautyScraper')
api.add_resource(allureScraper,'/allureScraper')
api.add_resource(bhgScraper,'/bhgScraper')
api.add_resource(cntravellerScraper,'/cntravellerScraper')
api.add_resource(cosmopolitanScraper,'/cosmopolitanScraper')
api.add_resource(dwellScraper,'/dwellScraper')
api.add_resource(gardensIllustratedScraper,'/gardensIllustratedScraper')
api.add_resource(graziaScraper,'/graziaScraper')
api.add_resource(inStyleScraper,'/inStyleScraper')
api.add_resource(livingetcScraper,'/livingetcScraper')
api.add_resource(maximScraper,'/maximScraper')
api.add_resource(realHomesScraper,'/realHomesScraper')
api.add_resource(realSimpleScraper,'/realSimpleScraper')
api.add_resource(styleAtHomeScraper,'/styleAtHomeScraper')
api.add_resource(southernLivingScraper,'/southernLivingScraper')
api.add_resource(solitaireScraper,'/solitaireScraper')
api.add_resource(teenVogueScraper,'/teenVogueScraper')
api.add_resource(theJewelryScraper,'/theJewelryScraper')
api.add_resource(womensHealthScraper,'/womensHealthScraper')
api.add_resource(vanityFairScraper,'/vanityFairScraper')
api.add_resource(travelPeacockScraper,'/travelPeacockScraper')
api.add_resource(travelAndLeisureIndiaScraper,'/travelAndLeisureIndiaScraper')
api.add_resource(townAndCountryScraper,'/townAndCountryScraper')
api.add_resource(professionalWomanScraper,'/professionalWomanScraper')
api.add_resource(motoringScraper,'/motoringScraper')
api.add_resource(moneyScraper,'/moneyScraper')
api.add_resource(indianJewelerScraper,'/indianJewelerScraper')
api.add_resource(stampingtonScraper,'/stampingtonScraper')
api.add_resource(elleDecor2Scraper,'/elleDecor2Scraper')
api.add_resource(flowerScraper,'/flowerScraper')
api.add_resource(gjepcScraper,'/gjepcScraper')
api.add_resource(instoreScraper,'/instoreScraper')
api.add_resource(verandaScraper,'/verandaScraper')
api.add_resource(theSpruceScraper,'/theSpruceScraper')
api.add_resource(romanticHomesScraper,'/romanticHomesScraper')
api.add_resource(nylonScraper,'/nylonScraper')
api.add_resource(nationalGeographicScraper,'/nationalGeographicScraper')
api.add_resource(lodgingScraper,'/lodgingScraper')
api.add_resource(houseBeautifulScraper,'/houseBeautifulScraper')
api.add_resource(hotelierScraper,'/hotelierScraper')
api.add_resource(gfmagScraper,'/gfmagScraper')
api.add_resource(foodAndWineScraper,'/foodAndWineScraper')
api.add_resource(femina,'/femina')
api.add_resource(elleDecorScraper,'/elleDecorScraper')
api.add_resource(countryLivingScraper,'/countryLivingScraper')
api.add_resource(anOtherScraper,'/anOtherScraper')




if __name__ == '__main__':
    app.run(debug = True)